### ISSUE TITLE
rock paper scissor 

### ISSUE THREAD

**Issue by Chris67813** [Chris67813/Project_132#10]
on my rock paper scissor game, the hand image is inverted, can you guys flip the image so it looks more natural, and can anyone also add a return to home button to return to the home page and startover button to replay the game. thank you

**Comment by AndrewMekhail** [comment]
Rotated The images of fists and mirrored it across the x-axis. also added a return to homepage button that triggers an empty javascript function (for you to create the function however you wish.) This created a subsequent issue where the images of the rock, paper and scissors that appear are all rotated incorrectly.  I will lodge this as a separate issue.
